### ISSUE TITLE
Lambda Invocation Payload Size Limitation

### ISSUE THREAD

**Issue by naomatheus** [NASA-IMPACT/nasa-apt#704] opened 2023-04-21 15:31 UTC
**Lambda Invocation Payload Size Limitation Issue and Potential Solutions**

### Issue

We are facing an issue with AWS Lambda's invocation payload size limitation of 6 MB, as specified in the AWS documentation: [AWS Lambda Limits](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html). This limitation is causing problems when handling larger pdf files in APT project.

### Potential Solutions

After discussing the issue, we have identified two potential solutions:

1. **Refactor infrastructure to use AWS Fargate and ECS**: By migrating our infrastructure to use AWS Fargate and the Elastic Container Service (ECS), we can avoid Lambda's payload size limitations. This option requires a more significant change to our current infrastructure and workflow.

2. **Provide temporary signed URLs for direct S3 object download**: This is the preferable solution. We can generate a temporary signed URL to allow the user's client (browser) to directly download larger objects from S3. This is a common practice used at Development Seed on projects such as CSDA. This solution is less invasive and allows us to maintain our current infrastructure and workflow.

### Conclusion

Considering the potential solutions, we recommend implementing the second option - providing temporary signed URLs for direct S3 object download. This approach is less disruptive to our existing infrastructure and follows best practices from similar projects. We should evaluate the feasibility and plan the implementation accordingly.

**Comment by naomatheus** [comment] 2023-04-21 19:57
Hey @sunu  it looks like creating signed URLs with boto3 is pretty simple for implementation. At least that is how it appears.
https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html#presigned-urls

**Comment by wrynearson** [comment] 2023-04-24 07:16
cc @batpad

**Comment by wrynearson** [comment] 2023-05-11 08:14
The PDF download portion is fixed, but upload (image or PDF) still needs to be addressed.

**Comment by wrynearson** [comment] 2023-07-20 09:01
Closing this because the issue is solved with resizing image uploads

**Closed as completed by wrynearson** 2023-07-20 09:01 UTC
Labels: function
