### ISSUE TITLE
Post-testing PDF Updates

### ISSUE THREAD

**Issue by aboydnw** [NASA-IMPACT/nasa-apt#474] opened 2022-03-07 23:03 UTC
### Acceptance Criteria

1.  If the ATBD is completed (if new workflow stage is not in scope, then use published date here), the date at the top of the PDF should show the completed (published, if no complete exists) date, not the current date
2. If the ATBD is not published, the date at the top of the PDF should be blank, not the current date 
3. There is a page break after the end of the Table of Contents
4. There is a header in the top right of the page that says "ATBD Generated by the Algorithm Publication Tool (APT)"

**Comment by aboydnw** [comment] 2022-03-07 23:04
@deborahUAH can you check the AC on this ticket? in particular, what should the date on a report be if it has not yet been published? and what would you like the header to say to indicate it is an APT generated ATBD? Does that header need to be on every page or just the front page?

**Comment by deborahUAH** [comment] 2022-03-07 23:28
If the ATBD is not yet completed, then the date should say "<to be date ATBD available in APT>" in the PDF.  If the ATBD is already completed and available to all users in APT, then the PDF date should be the date it was marked as completed.  I am trying to not use the word publish here since I need to reserve that term for discussing those ATBDs that take the path of getting published in the journal, for clarity between the two.    The header "This ATBD was generated by APT. <provide link to the ATBD>)".  I think it should be on every page, but open to other opinions.

**Comment by aboydnw** [comment] 2022-03-07 23:35
Okay, that is helpful on the draft ATBDs.

What specifically do you mean by completed? My understanding is we have Draft -> In Closed Review -> In Review (Open Review) -> In Publication -> Published
I am basing these stages off of this diagram:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/92742765/157136271-a40cb89e-835c-495e-9700-622bbeed9c62.png">



It sounds like you are saying that not all ATBDs will advance to the In Publication and Published stages, but I am unaware of a stage that is "Completed, but not Published." But there might be some functionality I am missing!

**Comment by deborahUAH** [comment] 2022-03-07 23:49
Regretfully, the term "in publication" and "published" came into use in a
time when we were not coordinating with the AGU journal.  Now that we are,
we need to be clearer about using the word published as indicating those
ATBDs that are going to be published in the AGU journal vs those that chose
not to go the journal route and the ATBD is instead "published", or just
made available to the public, in APT (all ATBDs will be in APT, some with
be what we call a green copy of a published (in the journal) ATBD and
others will the completed and now public ATBDs).

Does this make sense?
I'm not quite sure what to do about the issue now, but I am trying to be
careful and clear in this term use with users so as not to present the
wrong meaning - that an ATBD is published when it is not in a journal.
d

Deborah K Smith
Airborne Data Management Group (ADMG) Lead
NASA MSFC IMPACT Project
University of Alabama in Huntsville
Pronouns: she, her, hers
Google phone:  256-716-8189
Cell phone: 707494-5886

**Comment by aboydnw** [comment] 2022-03-08 00:15
Hm, okay that is helpful. So it sounds like we need a new stage after "In Review" and "In Publication"

We can go ahead and call it "Complete" unless there is another term that would work better.

Based on this, I have a couple initial questions:
1. Who would be the one to close out the Open Review and mark an ATBD as Complete? The Curator? Reviewer? Lead Author?
2. On the Curator dashboard, should we add "Complete" as a stage & metric?
3. On the Contributor dashboard, should we split the Public tab into Completed & Published?

Curator:
![image](https://user-images.githubusercontent.com/92742765/157140150-019de6fe-f592-4fd8-a184-d136cc651d1e.png)

Contributor:
![image](https://user-images.githubusercontent.com/92742765/157140200-443ad5fa-e1c5-4521-9ab3-d3eb699936ae.png)

**Comment by aboydnw** [comment] 2022-03-08 20:55
Created #480 to track this work

**Comment by leothomas** [comment] 2022-03-30 19:59
@deborahUAH : Currently, the date is only displayed in regular PDFs, not journal PDFs. The lack of date in the journal PDF is due to the agujournal style class. Is that the intended behaviour?

**Comment by leothomas** [comment] 2022-03-30 20:13
^follow up question, which format should be used for the date? Some options include: 
- ISO datetime: `2022-03-30 20:10:09.602866+00:00`
- ISO date: `2022-03-30`
- Full Text: `March 30th 2022`
- Full Text + time: `March 30th 2022 at 20:10:09`

**Comment by deborahUAH** [comment] 2022-03-31 00:07
@aboydnw  I just read through this ticket one more time and see I did not answer your question above:

Based on this, I have a couple initial questions:
Who would be the one to close out the Open Review and mark an ATBD as Complete? **The Curator**? Reviewer? Lead Author?
On the Curator dashboard, should we add "Complete" as a stage & metric?   Yes!
On the Contributor dashboard, should we split the Public tab into Completed & Published?  If the author is not going the journal route, then completed is only needed.  If they choose to publish in a journal, then completed and published would be appropriate except that it is the author that would know when the paper is published, not the APT curator, since we are not part of the publication process at this time (they submit the journal PDF to AGU and go through the process there).

**Comment by leothomas** [comment] 2022-04-01 19:11
@deborahUAH Couple questions about the `ATBD Generated by the Algorithm Publication Tool (APT)` header:
- Should that header be present only the title page? Or all pages? 
- Should that header be present on both the regular and journal pdfs? 
- Any specific font/colour/size to be used? 

Note: the AGU style class already adds a header to the top of each page of the journal pdf with the text `Manuscript submitted to ...` and then name of which ever journal is defined in the code (in this case `American Geophysical Union`). The text is in a light grey font and centered in the middle of the page (see screenshot below).

Should the `ATBD Generated by the Algorithm Publication Tool (APT)` header replace the `Manuscript submitted...` header? 
If not, how would you like the two to be positioned relative to each other

<img width="792" alt="image" src="https://user-images.githubusercontent.com/11858457/161326743-458adb51-8b88-44ac-9c73-82dc1f8479a5.png">

**Comment by deborahUAH** [comment] 2022-04-04 18:04
@leothomas  place the header on every page of the journal ATBD and for the regular ATBD.  A dark gray and smaller text is sufficient. 

For Journal ATBD it should say "manuscript submitted to Earth and Space Science" unless the author has indicated an alternate journal (I asked for this at one point, but I don't think it was implemented).  

The regular ATBD PDF should have a header on the title page only with "This ATBD was downloaded from the NASA Algorithm Publication Tool (APT)" .   I think "downloaded from" is better than "generated by".  @kaulfusa do you agree?

**Closed** 2022-04-19 15:11 UTC
